name: restaurant_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.1+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  animated_button: ^0.2.0
  bloc: ^8.1.2
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  fluttertoast: ^8.2.4
  google_fonts: ^6.1.0
  http: ^1.1.2
  lottie: ^2.7.0
  readmore: ^2.2.0

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/
