name: restaurant_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.2+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  android_alarm_manager_plus: ^3.0.4
  animated_button: ^0.2.0
  bloc: ^8.1.2
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_local_notifications: ^16.2.0
  fluttertoast: ^8.2.4
  google_fonts: ^6.1.0
  http: ^1.1.2
  intl: ^0.19.0
  lottie: ^2.7.0
  provider: ^6.1.1
  readmore: ^2.2.0
  rxdart: ^0.27.7
  shared_preferences: ^2.2.2

dev_dependencies:
  build_runner: ^2.4.7
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4

flutter:

  uses-material-design: true

  assets:
    - assets/
